// Mocks generated by Mockito 5.4.6 from annotations
// in online_exam_app/test/presentation/edit_profile/views_model/edit_profile_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:online_exam_app/api/requests/edit_profile_request/edit_profile_request.dart'
    as _i4;
import 'package:online_exam_app/domain/use_cases/edit_profile/edit_profile_use_case.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [EditProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditProfileUseCase extends _i1.Mock
    implements _i2.EditProfileUseCase {
  MockEditProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> invoke({required _i4.EditProfileRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [],
          {#request: request},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
