// Mocks generated by Mockito 5.4.6 from annotations
// in online_exam_app/test/api/data_source/edit_profile/remote_data_source/edit_profile_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:online_exam_app/api/client/api_client.dart' as _i8;
import 'package:online_exam_app/api/requests/edit_profile_request/edit_profile_request.dart'
    as _i15;
import 'package:online_exam_app/api/requests/email_verification_request/email_verification_request.dart'
    as _i12;
import 'package:online_exam_app/api/requests/forget_password_request/forget_password_email_request.dart'
    as _i11;
import 'package:online_exam_app/api/requests/login_request/login_request.dart'
    as _i10;
import 'package:online_exam_app/api/requests/reset_password_request/reset_password_request.dart'
    as _i14;
import 'package:online_exam_app/api/requests/signup_request/signup_request.dart'
    as _i13;
import 'package:online_exam_app/api/responses/edit_profile_response/edit_profile_response.dart'
    as _i7;
import 'package:online_exam_app/api/responses/email_verification_response/email_verification_response.dart'
    as _i4;
import 'package:online_exam_app/api/responses/forget_password_response/forget_password_email_response.dart'
    as _i3;
import 'package:online_exam_app/api/responses/login_response/login_response.dart'
    as _i2;
import 'package:online_exam_app/api/responses/reset_password_response/reset_password_response.dart'
    as _i6;
import 'package:online_exam_app/api/responses/signup_response/signup_response.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginResponse_0 extends _i1.SmartFake implements _i2.LoginResponse {
  _FakeLoginResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForgetPasswordEmailResponse_1 extends _i1.SmartFake
    implements _i3.ForgetPasswordEmailResponse {
  _FakeForgetPasswordEmailResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEmailVerificationResponse_2 extends _i1.SmartFake
    implements _i4.EmailVerificationResponse {
  _FakeEmailVerificationResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSignupResponse_3 extends _i1.SmartFake
    implements _i5.SignupResponse {
  _FakeSignupResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponse_4 extends _i1.SmartFake
    implements _i6.ResetPasswordResponse {
  _FakeResetPasswordResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEditProfileResponse_5 extends _i1.SmartFake
    implements _i7.EditProfileResponse {
  _FakeEditProfileResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i8.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.LoginResponse> login({required _i10.LoginRequest? request}) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#request: request}),
            returnValue: _i9.Future<_i2.LoginResponse>.value(
              _FakeLoginResponse_0(
                this,
                Invocation.method(#login, [], {#request: request}),
              ),
            ),
          )
          as _i9.Future<_i2.LoginResponse>);

  @override
  _i9.Future<_i3.ForgetPasswordEmailResponse> sendEmailVerification({
    required _i11.ForgetPasswordEmailRequest? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, [], {#request: request}),
            returnValue: _i9.Future<_i3.ForgetPasswordEmailResponse>.value(
              _FakeForgetPasswordEmailResponse_1(
                this,
                Invocation.method(#sendEmailVerification, [], {
                  #request: request,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.ForgetPasswordEmailResponse>);

  @override
  _i9.Future<_i4.EmailVerificationResponse> verifyEmailCode({
    required _i12.EmailVerificationRequest? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmailCode, [], {#request: request}),
            returnValue: _i9.Future<_i4.EmailVerificationResponse>.value(
              _FakeEmailVerificationResponse_2(
                this,
                Invocation.method(#verifyEmailCode, [], {#request: request}),
              ),
            ),
          )
          as _i9.Future<_i4.EmailVerificationResponse>);

  @override
  _i9.Future<_i5.SignupResponse> signup({
    required _i13.SignupRequest? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [], {#request: request}),
            returnValue: _i9.Future<_i5.SignupResponse>.value(
              _FakeSignupResponse_3(
                this,
                Invocation.method(#signup, [], {#request: request}),
              ),
            ),
          )
          as _i9.Future<_i5.SignupResponse>);

  @override
  _i9.Future<_i6.ResetPasswordResponse> resetPassword({
    required _i14.ResetPasswordRequest? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {#request: request}),
            returnValue: _i9.Future<_i6.ResetPasswordResponse>.value(
              _FakeResetPasswordResponse_4(
                this,
                Invocation.method(#resetPassword, [], {#request: request}),
              ),
            ),
          )
          as _i9.Future<_i6.ResetPasswordResponse>);

  @override
  _i9.Future<void> logout({required String? token}) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [], {#token: token}),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i7.EditProfileResponse> editProfile({
    required String? token,
    required _i15.EditProfileRequest? request,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#editProfile, [], {
              #token: token,
              #request: request,
            }),
            returnValue: _i9.Future<_i7.EditProfileResponse>.value(
              _FakeEditProfileResponse_5(
                this,
                Invocation.method(#editProfile, [], {
                  #token: token,
                  #request: request,
                }),
              ),
            ),
          )
          as _i9.Future<_i7.EditProfileResponse>);
}
